# Generated by Django 2.0.1 on 2018-03-22 12:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, choices=[('article', 'article'), ('book', 'book'), ('profile', 'profile'), ('website', 'website')], max_length=50, null=True)),
                ('og_title', models.CharField(blank=True, max_length=50, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='metadata')),
                ('twitter_card', models.CharField(choices=[('summary_large_image', 'summary large image'), ('app', 'app'), ('player', 'player')], max_length=50)),
                ('twitter_site', models.CharField(blank=True, help_text='Twitter handle. E.g. @cotidia', max_length=50, null=True)),
                ('twitter_title', models.CharField(blank=True, help_text='Title of the card', max_length=50, null=True)),
                ('twitter_description', models.TextField(blank=True, null=True)),
                ('twitter_creator', models.CharField(blank=True, help_text='Twitter handle. E.g. @cotidia', max_length=50, null=True)),
                ('twitter_image_src', models.ImageField(blank=True, null=True, upload_to='metadata')),
                ('twitter_image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_domain', models.CharField(blank=True, help_text='Page url', max_length=50, null=True)),
                ('google_type', models.CharField(blank=True, choices=[('Person', 'Person'), ('Organization', 'Organization'), ('WebSite', 'WebSite'), ('NewsArticle', 'NewsArticle')], max_length=50, null=True)),
                ('google_name', models.CharField(blank=True, max_length=50, null=True)),
                ('google_url', models.URLField(blank=True, null=True)),
                ('google_logo', models.ImageField(blank=True, null=True, upload_to='metadata')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'MetaData',
                'verbose_name_plural': 'MetaDatas',
                'ordering': ('order_id',),
            },
        ),
        migrations.CreateModel(
            name='MetaDataSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.PositiveIntegerField(default=0)),
                ('network', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('BEHANCE', 'Behance')], max_length=50)),
                ('url', models.URLField(max_length=250)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.MetaData')),
            ],
            options={
                'verbose_name': 'MetaData social network',
                'verbose_name_plural': 'MetaData social networks',
                'ordering': ('order_id',),
            },
        ),
    ]
