# Generated by Django 2.0.1 on 2018-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='google_url',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='og_url',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='twitter_domain',
        ),
        migrations.AlterField(
            model_name='metadata',
            name='google_logo',
            field=models.ImageField(blank=True, help_text='Recommended size: 112 x 112 px (min)', null=True, upload_to='metadata'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended size: 1200 x 630 px', null=True, upload_to='metadata'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='twitter_card',
            field=models.CharField(choices=[('summary_large_image', 'summary large image'), ('app', 'app'), ('player', 'player')], help_text='Type of Twitter card', max_length=50),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='twitter_image_src',
            field=models.ImageField(blank=True, help_text='Recommended size: 600 x 335 px', null=True, upload_to='metadata'),
        ),
    ]
