# Generated by Django 2.0.1 on 2018-04-15 07:32

import cotidia.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20180322_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='google_logo',
            field=cotidia.core.fields.PublicFileField(blank=True, help_text='Recommended size: 112 x 112 px (min)', null=True, upload_to='metadata'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='og_image',
            field=cotidia.core.fields.PublicFileField(blank=True, help_text='Recommended size: 1200 x 630 px', null=True, upload_to='metadata'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='twitter_image_src',
            field=cotidia.core.fields.PublicFileField(blank=True, help_text='Recommended size: 600 x 335 px', null=True, upload_to='metadata'),
        ),
    ]
